println("-----------------------Testing CPU Multi Core-------------------------------------")
backend = setBackend(:CPU)
println("Adding 4 cores to test multitrain algorithms")
addprocs(4)
@everywhere using FCANN
println("--------------------------------------------")
println("Testing archEval")
archEval(name, 100, 1024, [[1], [2], [3], [2, 2]])
println("TEST PASSED")
println()

println("Testing archEval with normLog cost function")
archEval(name, 100, 1024, [[1], [2], [3], [2, 2]], costFunc = "normLog")
println("TEST PASSED")
println()

rm(string("archEval_", name, "_", M, "_input_", O, "_output_ADAMAX", backend, "_absErr.csv"))
rm(string("archEval_", name, "_", M, "_input_", O, "_output_ADAMAX", backend, "_normLog.csv"))

println("Testing evalLayers")
evalLayers(name, 100, 1024, [100, 200], layers=[2, 4])
println("TEST PASSED")
println()

rm(string("evalLayers_", name, "_", M, "_input_", O, "_output_0.002_alpha_ADAMAX", backend, "_absErr.csv"))

println("Testing smartEvalLayers")
smartEvalLayers(name, 100, 1024, [100, 200], layers=[1, 2], tau=0.05f0)
println("TEST PASSED")
println()

rm(string("evalLayers_", name, "_", M, "_input_", O, "_output_100_epochs_smartParams_ADAMAX", backend, "_absErr.csv"))

println("Testing multiTrain")
multiTrain(name, 200, 1024, [2, 2], 0.0f0, 1.0f0, 0.002f0, 0.1f0, 6, 1)
multiTrain(name, 200, 1024, [2, 2], 0.0f0, 1.0f0, 0.002f0, 0.1f0, 6, 2)
multiTrain(name, 200, 1024, [2, 2], 0.0f0, 1.0f0, 0.002f0, 0.1f0, 6, 1, costFunc = "normLog")
multiTrain(name, 200, 1024, [2, 2], 0.0f0, 1.0f0, 0.002f0, 0.1f0, 6, 2, costFunc = "normLog")
println("TEST PASSED")
println()

println("Testing evalMulti")
evalMulti(name, [2, 2], 0.0f0, 1.0f0, 0.002f0, 0.1f0, IDList = [1, 2])
evalMulti(name, [2, 2], 0.0f0, 1.0f0, 0.002f0, 0.1f0, IDList = [1, 2], costFunc = "normLog")
println("TEST PASSED")
println()

filename = string(name, "_", M, "_input_2X2_hidden_", O, "_output_0.002_alpha_0.1_decay_1.0_maxNorm_ADAMAX_absErr")

rm(string("1_multiParams_", filename, ".bin"))
rm(string("1_multiPerformance_", filename, ".csv"))
rm(string("1_multiPredScatTrain_", filename, ".csv"))
rm(string("1_multiPredScatTest_", filename, ".csv"))
rm(string("2_multiParams_", filename, ".bin"))
rm(string("2_multiPerformance_", filename, ".csv"))
rm(string("2_multiPredScatTrain_", filename, ".csv"))
rm(string("2_multiPredScatTest_", filename, ".csv"))
rm(string("fullMultiParams_", filename, ".bin"))
rm(string("fullMultiPerformance_", filename, ".csv"))
rm(string("multiPredScatTrain_", filename, ".csv"))
rm(string("multiPredScatTest_", filename, ".csv"))

filename = string(name, "_", M, "_input_2X2_hidden_", O, "_output_0.002_alpha_0.1_decay_1.0_maxNorm_ADAMAX_normLog")

rm(string("1_multiPerformance_", filename, ".csv"))
rm(string("1_multiPredScatTrain_", filename, ".csv"))
rm(string("1_multiPredScatTest_", filename, ".csv"))
rm(string("1_multiParams_", filename, ".bin"))
rm(string("2_multiPerformance_", filename, ".csv"))
rm(string("2_multiPredScatTrain_", filename, ".csv"))
rm(string("2_multiPredScatTest_", filename, ".csv"))
rm(string("2_multiParams_", filename, ".bin"))
rm(string("fullMultiPerformance_", filename, ".csv"))
rm(string("multiPredScatTrain_", filename, ".csv"))
rm(string("multiPredScatTest_", filename, ".csv"))
rm(string("fullMultiParams_", filename, ".bin"))

# Remove generated files
rm("Xtrain_test.csv")
rm("Xtest_test.csv")
rm("ytrain_test.csv")
rm("ytest_test.csv")
rm("Xtrain_test.bin")
rm("Xtest_test.bin")
rm("ytrain_test.bin")
rm("ytest_test.bin")

# filename = string(name, "_10_input_", [], "_hidden_2_output_0.0_L2_Inf_maxNorm_0.002_alpha_ADAMAX", backend, "_absErr")
# rm(string("1_costRecord_", filename, ".csv"))
# rm(string("1_timeRecord_", filename, ".csv"))
# rm(string("1_performance_", filename, ".csv"))
# rm(string("1_params_", filename, ".bin"))

filename = string(name, "_10_input_2X2_hidden_2_output_0.002_alpha_0.1_decay_ADAMAX_absErr")
rm(string("1_costRecord_", filename, ".csv"))
rm(string("1_timeRecord_", filename, ".csv"))
rm(string("1_performance_", filename, ".csv"))
rm(string("1_predScatTest_", filename, ".csv"))
rm(string("1_predScatTrain_", filename, ".csv"))
rm(string("1_params_", filename, ".bin"))

# rm(string("2_costRecord_", filename, ".csv"))
# rm(string("2_timeRecord_", filename, ".csv"))
# rm(string("2_performance_", filename, ".csv"))
# rm(string("2_params_", filename, ".bin"))

rm("testParams1")
rm("testParams2")